site_name: MoulConfig
site_description: MoulConfig is a config library for Minecraft mods with multi version ambitions
site_author: Linnea Gräf
site_url: https://notenoughupdates.org/MoulConfig

repo_name: MoulConfig
repo_url: https://github.com/NotEnoughUpdates/MoulConfig
edit_uri: edit/master/src/doc/docs/
copyright: 'Copyright &copy; 2023 Linnea Gräf'

plugins:
  - zettelkasten

theme:
  name: zettelkasten-solarized-light
  social:
    - type: 'github'
      link: 'https://github.com/notenoughupdates/moulconfig'
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.top


nav:
  - Home:
      - index.md
  - Config:
      - config/index.md
  - Javadocs:
      - Home: javadocs/index.html
      - Common: javadocs/common/index.html
      - Legacy: javadocs/legacy/index.html
      - Annotations: javadocs/common/io.github.notenoughupdates.moulconfig.annotations/index.html