name: Update Javadoc
on:
  push:
    tags:
      - '*'
  workflow_dispatch: { }

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Generate JavaDoc
        run: |
          ./gradlew compileAllDocs --stacktrace
      - name: Upload JavaDoc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/allDocs