name: Release
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_moulconfigPassword: ${{ secrets.MAVENPASS }}
          ORG_GRADLE_PROJECT_moulconfigUsername: moulconfig
        run: |
          ./gradlew publish --stacktrace
